development:
 database: 
 username: 
 password: 
 host: 
     
test:
 database: 
 username: 
 password: 
 host: 

production:
 database: 
 username: 
 password: 
 host: 

file_storage:
 storage_type: remote   # remote or local
 storage_ssh:    # username@host; remove this line if you are using local storage. 
 storage_path: nutmegunit.com/public/files